#!/usr/bin/env bash

VIEW_SOURCE="$(dirname $0)/../shared/template"
VIEW_DEST="$(dirname $0)/../shared/view"

mkdir -p $VIEW_DEST

for f in $(ls "$VIEW_SOURCE"/*.html); do
  f="$(basename $f)"
  f="$VIEW_DEST/${f:0:$((${#f}-5))}"
  echo 'module.exports = (render, model) => render`' > "$f.js"
  cat "$VIEW_SOURCE/$(basename $f).html" >> "$f.js"
  echo '`;' >> "$f.js"
done